#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Find the PID of the process.
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Stop the process using pkill.
if [ -n "$pid" ]; then
  pkill -P "$pid"
  pkill -9 -P "$pid"
fi
