#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100, with "FizzBuzz" for multiples of 3 and 5, "Fizz" for multiples of 3, "Buzz" for multiples of 5, and the number itself otherwise

for i in {1..100}
do
  if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
  then
    echo "FizzBuzz"
  elif [ $((i % 3)) -eq 0 ]
  then
    echo "Fizz"
  elif [ $((i % 5)) -eq 0 ]
  then
    echo "Buzz"
  else
    echo $i
  fi
done
