#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes

count=0
while [ $count -lt 719 ]
do
  if [ $((count % 60)) -eq 0 ]
  then
    echo "Hour: $((count / 60))"
  else
    echo $((count % 60))
  fi
  ((count++))
done
